### ISSUE TITLE
MVP 3: Booking

### ISSUE THREAD

**Issue by homelissa** [homelissa/hipcamp#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Seeded with info to demonstrate this feature

**Comment by xnanodax** [comment]
Great work with the booking MVP! 

## Functionality 

- [ ] When I delete a booking, I get directed to my user show page but its blank. Is this correct?

## Styling:
- HipCamp
![screen shot 2018-06-14 at 8 09 14 am](https://user-images.githubusercontent.com/20424731/41420888-56c9e168-6faa-11e8-99a8-cdfde9d0ff42.png)

- HippyCamp
![screen shot 2018-06-14 at 8 09 19 am](https://user-images.githubusercontent.com/20424731/41420879-51002e7c-6faa-11e8-8af6-a180b6131aea.png)

I would add a toggle + and - to change the number of people.

**Comment by homelissa** [comment]
Yes, right now the user show page only shows the user's booking requests. So if the user deletes all all booking requests, there is nothing to show.

**Comment by xnanodax** [comment]
Oh! I see. I would suggest to add some type of default view so the user doesnt think it is a bug because right now, the entire page is blank. 

I would suggest a page that looks like this from HipCamp.

![screen shot 2018-06-14 at 9 47 33 am](https://user-images.githubusercontent.com/20424731/41426308-11cb9030-6fb8-11e8-9de0-8e05541737e3.png)

**Comment by homelissa** [comment]
The user's show page now includes information about the user and the number of booking requests/trips. Can you take a look?

**Comment by xnanodax** [comment]
Awesome work adding a confirmation page! 

## Frontend Suggestions
1) Add a link to the welcome message to the user profile page if they wanted to see their list of bookings without making a new booking. 

2) Add the number of tickets to display on the confirmation page since you already have that on your state.

3) Its hard for a user to see the Upcoming trips header based on its font size and position. Either add <hr> right above the Upcoming Trips header OR make header bigger. 


## Future fix:
- [ ] There is a little bit of nested ness in your state shape with bookings.listings since it is holding the actual listing object instead of the listing id. 
![screen shot 2018-06-15 at 9 54 11 am](https://user-images.githubusercontent.com/20424731/41480094-275e9eea-7082-11e8-85c7-4ab1f189f3a2.png)

**Comment by homelissa** [comment]
The frontend suggestions have been implemented!

**Comment by xnanodax** [comment]
Awesome! This issue is done!
